spring:
  application:
    name: Library-Management-Application
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  thymeleaf:
    check-template-location: false

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

app:
  admin:
    email: ${INITIAL_ADMIN_EMAIL:admin@admin.com}
    password: ${INITIAL_ADMIN_PASSWORD:admin}
  upload:
    dir: ${UPLOAD_DIR:uploads}
