CREATE TABLE authors
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL,
    birth_date  DATE,
    nationality VARCHAR(255),
    biography   VARCHAR(1000)
);
