CREATE TABLE members
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name       VARCHAR(255) NOT NULL,
    last_name        VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    phone            VARCHAR(255),
    membership_date  DATE,
    CONSTRAINT uk_members_email UNIQUE (email)
);
