CREATE TABLE books
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255)  NOT NULL,
    isbn             VARCHAR(255)  NOT NULL,
    publish_year     INTEGER,
    description      VARCHAR(1000),
    total_copies     INTEGER       NOT NULL,
    available_copies INTEGER       NOT NULL,
    category_id      BIGINT,
    cover_image      VARCHAR(255),
    version          BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uk_books_isbn UNIQUE (isbn),
    CONSTRAINT fk_books_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX idx_books_category_id ON books (category_id);
