CREATE TABLE loans
(
    borrow_date TIMESTAMP    NOT NULL,
    due_date    TIMESTAMP    NOT NULL,
    return_date TIMESTAMP,
    status      VARCHAR(20)  NOT NULL,
    member_id   BIGINT       NOT NULL,
    book_id     BIGINT       NOT NULL,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CONSTRAINT fk_loans_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_loans_book FOREIGN KEY (book_id) REFERENCES books (id)
);

CREATE INDEX idx_loans_member_id ON loans (member_id);
CREATE INDEX idx_loans_book_id ON loans (book_id);
