apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: library-production

resources:
  - ../../base

# The CI job "update-gitops-state" updates this on every push to `production`, using the
# new `sha-<commit>` tag. We never use `latest` here. Production only gets an image after
# it was already tested in `dev` and `staging`.
images:
  - name: library-management-application
    newTag: unset
